### PR TITLE
Update to some package versions

### PR DESCRIPTION
**Pull request by cyramic**

### CODE REVIEW

**Comment by tab1tha** [comment]
testing these changes.

**Comment by cyramic** [comment]
I think there's been too many updates since here to make it worth testing.  I'd close this, and apply the needed changes to a new PR.

**Comment by tab1tha** [comment]
Sure. 
What command generated the changes in this pull request? `npm update`?

**Comment by cyramic** [comment]
Closing as it was handled by other 

> Sure. What command generated the changes in this pull request? `npm update`?

I believe so, yes.

**Pull request closed without merging**
